### ISSUE TITLE
[Deliverable #4]

### ISSUE THREAD

**Issue by Alex-Craig** [Berea-CS-Courses/capstone-project-Alex-Craig#9]
__One sentence overview of your submission__
For my Midterm documentation I have finished my shortcuts version of the app and have updated my previous deliverables according to comments and feedback.

__I would like feedback on ...__ 
My shortcuts version of the app, which can be found here: https://bit.ly/3cky7PO. (IOS Devices and Shortcuts App Required)
Instructions:
To begin go to the link above and click "Add Shortcut" this will add the Restaurant Roulette to your shortcut app and will show you the completed code that I have. Then by clicking on 3 dots in the box will allow you to go into the code and change the list of restaurant types to your liking. Then you can in the code, scroll until you find Allow Access for calls, location, notifications, and opening shortcuts to have the code run more smooth without asking questions.

**Comment by schweinsbergs** [comment]
So, I think what you have for a prototype definitely works to show you what you would like to have accomplished. 

What I do wonder, though, is you've mentioned that you plan on restarting the app and that there are limitations in shortcuts that make you need to restart the project with a different program. I think it would be a useful reference for yourself and those grading to lay out what those problems are, why you need to switch, and what functionality exactly you're looking for so you know what to research for your next medium.

**Comment by robinsonkal** [comment]
I think for your prototype it would be very useful to have a video showing app progress and features. But I also realize that doing this in GitHub can be difficult and also filming a phone screen can be a process. Other than that, the documentation is pretty well designed. Maybe adding some titles to your pictures could make them easier to understand.

**Comment by alfarozavalae** [comment]
Good documentation of the steps required to run your proof of concept. The ability to allow users to test using the link is useful specially now that you are actually working on some code. 
I see that you documented some updates to previous deliverables but I do not think you actually went back to make these changes in each deliverables. Please go back and do that so that the whole project is updated. The instructions for D4 stated that you need to add the images with a one-sentence description of each of them, this is something that would have been helpful to better understand what you worked on this week. 
I know you are feeling a bit discouraged about switching from the shortcuts to a different app development program so as usual, feel free to reach out with specific questions on this. Googling if "x is possible in AppInventor" might be an easy way to have some of your questions answered so that you can decide which program to look into. Android Studio uses Java but (just like Sam in our pod) you could give something like Kivy a try if you feel like using Python for this might be better. Please continue to make progress by setting your own milestones and adding issues. Great work so far!
